# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile
- task: UniversalPackages@0
  inputs:
    command: 'download'
    downloadDirectory: '$(System.DefaultWorkingDirectory)'
    feedsToUse: 'internal'
    vstsFeed: '8810dc24-af07-43fa-a506-de5fe945f20e'
    vstsFeedPackage: '200cae98-bc0b-45a1-b539-e4a6932fb351'
    vstsPackageVersion: '19.7.863'
- task: CmdLine@2
  inputs:
    script: |
      sudo mv $(System.DefaultWorkingDirectory)/twistcli /usr/bin/twistcli
      sudo chmod +x /usr/bin/twistcli
- task: twistcli-scan@1
  inputs:
    scanType: 'images'
    twistlockService: 'Twistlock'
    vulnerabilityThreshold: 'critical'
    onlyFixed: false
    gracePeriod: '0'
    complianceThreshold: 'critical'
    artifact: '$(imageName):$(Build.BuildId)'
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Visual Studio Enterprise(96d4b62f-baef-4895-8e45-04b69e063cc3)'
    azureContainerRegistry: '{"loginServer":"vpersadacrdemobuild.azurecr.io", "id" : "/subscriptions/96d4b62f-baef-4895-8e45-04b69e063cc3/resourceGroups/vpersaddemobuildazure/providers/Microsoft.ContainerRegistry/registries/vpersadacrdemobuild"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Push services'
    includeLatestTag: true