# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'visdocker'
        repository: 'osi'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
#Aqua scanning
- stage: acrlogin
  jobs:
  - job: login
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'visdocker'
        command: 'login'
- stage: acrlogin1
  jobs:
  - job: login
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'testaqua'
        command: 'login'
- stage: aquatest
  jobs:
  - job: scan
    steps:
     - task: aquasecScanner@4
       inputs:
         image: '$(Build.Repository.Name):$(Build.BuildId)'
         scanType: 'local'
         register: false
         hideBase: false
         showNegligible: false
         windowsScannerVersion: '4.2.0'
         scanner: 'testaqua.azurecr.io/aquasec/scanner:4.2.19297'
         registry: '$(Build.Repository.Name)'
         connection: 'Aquasanner1'
         caCertificates: true