apiVersion : apps/v1
kind: Deployment
metadata:
  name: akspipeline 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akspipeline
  template:
    metadata:
      labels:
        app: akspipeline 
    spec:
      containers:
        - name: akspipeline 
          image: akdemoregistry.azurecr.io/akspipeline
          ports:
          - containerPort: 8080