name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      servicePrincipal: ${{ '5a16e934-8d13-408b-b529-e74d8b3e83c5' }}
      servicePrincipalPassword: ${{'a25c356e-355e-492d-9dc7-fd78fccae032' }}
      tenantId: ${{'b0ffe258-28bd-45c7-a0cf-de344ee768f7' }}
      imageRepository: ${{ 'nimaipipelinesjavascriptdocker' }}
      containerRegistry: ${{ 'nimaicontainerregistry.azurecr.io' }}
    steps:
      - name: Azure Container Registry Build
        uses: ams0/acr-task-github-action@v1
        with:
          image: ${{ env.imageRepository }}
          service_principal: ${{ env.servicePrincipal }}
          service_principal_password: ${{ env.servicePrincipalPassword }}
          repository: ${{ env.imageRepository }}
          registry: ${{ env.containerRegistry }}
          tenant: ${{ env.tenantId }}
          dockerfile: ${{ './app/Dockerfile' }}

